---
javascripts:
- base:
  - jquery
  - jquery.livequery
  - fonts/cufon-yui
  - fonts/Hand_Of_Sean_400.font
  - jquery-ui-1.8.5.custom.min
  - jquery.nivo.slider
  - supersized.2.0
  - jquery.scrollTo-min
  - jquery.url
  - application
- openlayer:
  - OpenLayers
  - cloudmade
stylesheets:
- base:
  - layout
  - jquery-ui-1.8.5.custom

