development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: methanehydrates_development
  username: postgres
  password:

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: methanehydrates_test
  username: postgres
  password:

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: methanehydrates_production
  username: postgres
  password:
